# Generated by Django 5.2.8 on 2026-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='owner',
        ),
        migrations.AddField(
            model_name='bike',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
